### ISSUE TITLE
limit in inner layer SQL will return error result

### ISSUE THREAD

**Issue by even986025158** [StarRocks/starrocks#11780]
### Steps to reproduce the behavior (Required)
select count(1) from (select * from table limit 10)t where 1=1 ;

return error result  10

### Expected behavior (Required)
return 10

### Real behavior (Required)
return 30   [3BE]

### StarRocks version (Required)
2.0.9

**Comment by kangkaisen** [comment]
This issue has been fixed, you could try 2.2 or 2.3 latest version.

**Comment by yangrong688** [comment]
> This issue has been fixed, you could try 2.2 or 2.3 latest version and check it.

Hi @kangkaisen , we still encounter this problem in StarRocks 2.3.2-dbc89ae in test enviornment, StarRocks 2.1.12 works fine with ().

case to reproduce:

CREATE TABLE `t1` (
  `id` bigint(20) NOT NULL COMMENT "",
  `column1` varchar(20) NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`id`)
COMMENT "test"
DISTRIBUTED BY HASH(`id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);

insert into t1 
select 1,"a"
union
select 2,"b"
union
select 3,"c"
union
select 4,"d"
;

sql1:
(SELECT * from t1 where id > 1 order by id desc limit 1)
;

execute this sql and returns the follow results:
id    column1
2	b
3	c
4	d

sql2:
SELECT * from t1 where id > 1 order by id desc limit 1;

execute this sql and returns the follow results:
id    column1
4	d

sql1 return error results, sql2 return correct results, please help to fix it, thank you.
