### ISSUE TITLE
Error "Warehouse id: 0 not  exist."

### ISSUE THREAD

**Issue by Dan-J-D** [StarRocks/starrocks#51576]
### Steps to reproduce the behavior (Required)
1. Create a frontend & backend in the same docker compose file.
2. Start docker compose & add the backend as a backend in the front end.
3. Create a database & a table under it.
4. Create a routine load to the table from a kafka stream.
5. Stop both instances by pressing CTRL+C
6. Wait for both all instances to stop
7. Start up the instances again

### Expected behavior (Required)
```
starrocks-fe-0  | WARNING: Exception thrown during asynchronous load
starrocks-fe-0  | java.util.concurrent.CompletionException: com.starrocks.common.ErrorReportException: Warehouse id: 0 not 
exist.
starrocks-fe-0  |       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)    
starrocks-fe-0  |       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)  
starrocks-fe-0  |       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)   
starrocks-fe-0  |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)       
starrocks-fe-0  |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)       
starrocks-fe-0  |       at java.base/java.lang.Thread.run(Thread.java:829)
starrocks-fe-0  | Caused by: com.starrocks.common.ErrorReportException: Warehouse id: 0 not exist.
starrocks-fe-0  |       at com.starrocks.common.ErrorReportException.report(ErrorReportException.java:38)
starrocks-fe-0  |       at com.starrocks.server.WarehouseManager.getWarehouse(WarehouseManager.java:91)
starrocks-fe-0  |       at com.starrocks.server.WarehouseManager.getBackgroundWarehouse(WarehouseManager.java:258)
starrocks-fe-0  |       at com.starrocks.statistic.StatisticUtils.buildConnectContext(StatisticUtils.java:111)
starrocks-fe-0  |       at com.starrocks.sql.optimizer.statistics.ColumnBasicStatsCacheLoader.lambda$asyncLoadAll$1(ColumnBasicStatsCacheLoader.java:91)
starrocks-fe-0  |       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)   
starrocks-fe-0  |       ... 3 more
```

### Real behavior (Required)
Nothing.

### StarRocks version (Required)
 - 3.3.3-312ed45

**Comment by kevincai** [comment]
@Dan-J-D do you have a complete stacktrace for the exception?

**Comment by LiShuMing** [comment]
should be fixed by this(https://github.com/StarRocks/starrocks/pull/51388/files), can you check it by applying this pr?

**Comment by haifzhu** [comment]
> should be fixed by this(https://github.com/StarRocks/starrocks/pull/51388/files), can you check it by applying this pr?

i also encounter the issue and i user the newest version starrocks 3.3.6, the issue still exist. That's mean, the issue can not be fixed by the commit(https://github.com/StarRocks/starrocks/pull/51388/files).

**Comment by kevincai** [comment]
@haifzhu do you have the fe log for the error?

**Comment by lllwan** [comment]
@kevincai I encountered the same issue as well.    
`Nov 24, 2024 4:00:38 PM com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncBulkCompleter accept
WARNING: Exception thrown during asynchronous load
java.util.concurrent.CompletionException: com.starrocks.common.ErrorReportException: Warehouse id: 0 not exist.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.starrocks.common.ErrorReportException: Warehouse id: 0 not exist.
        at com.starrocks.common.ErrorReportException.report(ErrorReportException.java:38)
        at com.starrocks.server.WarehouseManager.getWarehouse(WarehouseManager.java:91)
        at com.starrocks.server.WarehouseManager.getBackgroundWarehouse(WarehouseManager.java:258)
        at com.starrocks.statistic.StatisticUtils.buildConnectContext(StatisticUtils.java:113)
        at com.starrocks.sql.optimizer.statistics.TableStatsCacheLoader.lambda$asyncLoadAll$2(TableStatsCacheLoader.java:67)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        ... 3 more

Nov 24, 2024 4:00:38 PM com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncBulkCompleter accept
WARNING: Exception thrown during asynchronous load
java.util.concurrent.CompletionException: com.starrocks.common.ErrorReportException: Warehouse id: 0 not exist.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.starrocks.common.ErrorReportException: Warehouse id: 0 not exist.
        at com.starrocks.common.ErrorReportException.report(ErrorReportException.java:38)
        at com.starrocks.server.WarehouseManager.getWarehouse(WarehouseManager.java:91)
        at com.starrocks.server.WarehouseManager.getBackgroundWarehouse(WarehouseManager.java:258)
        at com.starrocks.statistic.StatisticUtils.buildConnectContext(StatisticUtils.java:113)
        at com.starrocks.sql.optimizer.statistics.ColumnBasicStatsCacheLoader.lambda$asyncLoadAll$1(ColumnBasicStatsCacheLoader.java:91)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        ... 3 more

Nov 24, 2024 4:00:38 PM com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncBulkCompleter accept
WARNING: Exception thrown during asynchronous load
java.util.concurrent.CompletionException: com.starrocks.common.ErrorReportException: Warehouse id: 0 not exist.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.starrocks.common.ErrorReportException: Warehouse id: 0 not exist.
        at com.starrocks.common.ErrorReportException.report(ErrorReportException.java:38)
        at com.starrocks.server.WarehouseManager.getWarehouse(WarehouseManager.java:91)
        at com.starrocks.server.WarehouseManager.getBackgroundWarehouse(WarehouseManager.java:258)
        at com.starrocks.statistic.StatisticUtils.buildConnectContext(StatisticUtils.java:113)
        at com.starrocks.sql.optimizer.statistics.TableStatsCacheLoader.lambda$asyncLoadAll$2(TableStatsCacheLoader.java:67)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        ... 3 more`

**Comment by lllwan** [comment]
Another error message（my cluster only has one FE node.）： 2024-11-24 16:02:53.272+08:00 WARN (stateChangeExecutor|79) [LoadJobMVListener.triggerToRefreshRelatedMVs():121] refresh mv after publish version failed: java.lang.IllegalStateException: Current node is not leader, but INIT, submit log is not allowed
at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
at com.starrocks.persist.EditLog.submitLog(EditLog.java:1231)
at com.starrocks.persist.EditLog.logEdit(EditLog.java:1219)
at com.starrocks.persist.EditLog.logTaskRunCreateStatus(EditLog.java:1356)
at com.starrocks.scheduler.TaskRunManager.submitTaskRun(TaskRunManager.java:75)
at com.starrocks.scheduler.TaskManager.executeTaskAsync(TaskManager.java:359)
at com.starrocks.scheduler.TaskManager.executeTask(TaskManager.java:308)
at com.starrocks.server.LocalMetastore.executeRefreshMvTask(LocalMetastore.java:3427)
at com.starrocks.server.LocalMetastore.refreshMaterializedView(LocalMetastore.java:3468)
at com.starrocks.server.LocalMetastore.refreshMaterializedView(LocalMetastore.java:3452)
at com.starrocks.listener.LoadJobMVListener.doTriggerToRefreshRelatedMVs(LoadJobMVListener.java:155)
at com.starrocks.listener.LoadJobMVListener.triggerToRefreshRelatedMVs(LoadJobMVListener.java:119)
at com.starrocks.listener.LoadJobMVListener.onInsertOverwriteJobCommitFinish(LoadJobMVListener.java:84)
at com.starrocks.listener.GlobalLoadJobListenerBus.lambda

**Comment by kevincai** [comment]
> Another error message（my cluster only has one FE node.）： 2024-11-24 16:02:53.272+08:00 WARN (stateChangeExecutor|79) [LoadJobMVListener.triggerToRefreshRelatedMVs():121] refresh mv after publish version failed: java.lang.IllegalStateException: Current node is not leader, but INIT, submit log is not allowed at com.google.common.base.Preconditions.checkState(Preconditions.java:512) at com.starrocks.persist.EditLog.submitLog(EditLog.java:1231) at com.starrocks.persist.EditLog.logEdit(EditLog.java:1219) at com.starrocks.persist.EditLog.logTaskRunCreateStatus(EditLog.java:1356) at com.starrocks.scheduler.TaskRunManager.submitTaskRun(TaskRunManager.java:75) at com.starrocks.scheduler.TaskManager.executeTaskAsync(TaskManager.java:359) at com.starrocks.scheduler.TaskManager.executeTask(TaskManager.java:308) at com.starrocks.server.LocalMetastore.executeRefreshMvTask(LocalMetastore.java:3427) at com.starrocks.server.LocalMetastore.refreshMaterializedView(LocalMetastore.java:3468) at com.starrocks.server.LocalMetastore.refreshMaterializedView(LocalMetastore.java:3452) at com.starrocks.listener.LoadJobMVListener.doTriggerToRefreshRelatedMVs(LoadJobMVListener.java:155) at com.starrocks.listener.LoadJobMVListener.triggerToRefreshRelatedMVs(LoadJobMVListener.java:119) at com.starrocks.listener.LoadJobMVListener.onInsertOverwriteJobCommitFinish(LoadJobMVListener.java:84) at com.starrocks.listener.GlobalLoadJobListenerBus.lambda

This exception trace is truncated, can you paste a full exception trace? @lllwan
